@startuml
title 小程序主页搜索-代码调用流程
|移动端主线程|
start
repeat
:ChatbotMainActivity.onSearchTextChanged|ChatbotMainActivity.onEditorAction;
:ChatbotMainActivity.startSearch;
:ChatbotMainActivity.initEmptyAndListViewState;
repeat while (TextUtils.isEmpty(text)) is (yes)
:ChatbotMainActivity.sendEmptyMessageDelayed;
-[#black,dotted]->
|#AntiqueWhite|移动端数据库|
:ChatbotMainViewModel.inputDbSearch;
:ChatbotMainViewModel.onQueryComplete;
:ChatbotUtils.resetData;
:ChatbotMainViewModel.setValue;
-[#black,dotted]->
|移动端主线程|
:ChatbotMainActivity.observerData;
fork
    :mViewModel.mInputDbSearchList.observe;
    :hasInputDbSearchData = false;
    if (ChatbotUtils.isEmptyList(chatbotSearchListEntities)) then (no)
        :hasInputDbSearchData = true;
        :mChatbotSearchListAdapter.setInputSearchDbData;
        :ChatbotMainActivity.initEmptyAndListViewState;
        :ChatbotMainActivity.setLoadMoreState;
        detach
    else if (hasInputNetSearch) then (no)
        :ChatbotMainActivity.initEmptyAndListViewState;
        detach
        else
         :让网络请求处理;
         detach
    endif
fork again
    :hasInputNetSearch = false;
    if (ChatbotUtils.isNetWorkDisconnect(mActivity)) then (no)
        :MessageUtils.showToast;
        detach
    else if (TelephonyConfig.getInstance().getActiveSimCount() > 0) then (no)
            :不能网络搜索;
            detach
    endif
endfork
:hasInputNetSearch = true;
:ChatbotMainViewModel.inputDbSearch;
-[#black,dotted]->
|#AntiqueWhite|服务端|
:ChatbotApi.getInstance().requestChatbotList;
-[#black,dotted]->
|移动端主线程|
:ChatbotUtils.resetData;
:ChatbotMainViewModel.postValue;
:ChatbotMainActivity.observerData;
if (ChatbotUtils.isEmptyList(list)) then (yes)
    :ChatbotMainActivity.setLoadMoreState;
    if (hasInputDbSearchData) then (yes)
        :ChatbotMainActivity.initEmptyAndListViewState;
        detach
    else
        :本地搜索有数据，有显示了;
        detach
    endif
else (no)
    if (list.size() < ChatbotCommon.SearchList.SHOW_MAX_ITEMS) then (yes)
        :ChatbotMainActivity.setLoadMoreState;
        detach
    else (yes)
        :ChatbotMainActivity.setLoadMoreState;
        :mChatbotSearchListAdapter.setInputSearchNetData;
        -[#black,dotted]->
        |#AntiqueWhite|移动端子线程|
        :ChatbotSearchListAdapter.markChatbot;
        :ChatbotSearchListAdapter.sendMessage;
        -[#black,dotted]->
        |移动端主线程|
        :activity.mChatbotSearchListAdapter.notifyDataSetInputSearch;
        :ChatbotMainActivity.initEmptyAndListViewState;
    endif
endif
stop
@enduml