@startuml
ComposeMessageActivity --> ComposeMessageActivity: onClick
ComposeMessageActivity --> ComposeMessageActivity: rcsSend
ComposeMessageActivity --> ComposeMessageActivity: confirmSendMessageIfNeeded
ComposeMessageActivity --> ComposeMessageActivity: sendMessage
ComposeMessageActivity -> WorkingMessage: send
WorkingMessage --> WorkingMessage: sendRcsMessage
WorkingMessage --> WorkingMessage: preSendRcsSmsWorker
WorkingMessage --> WorkingMessage: sendRcsSmsWorker
WorkingMessage --> WorkingMessage: sendRcsText
WorkingMessage -> MessageApi: sendText
MessageApi -> ServiceApi: sendText
ServiceApi -> IServiceApi: sendText
IServiceApi -> ServiceApiImpl: sendText
ServiceApiImpl -> MessageManager: sendText
MessageManager -> MessageQueue: addMessageToQueue

MessageHandler --> MessageHandler: send
MessageHandler --> MessageHandler: sendInstantMessage
MessageHandler -> TransferUtil: putMessage
TransferUtil -> RcsStack: putMessage
RcsStack -> apiJNI: RcsStack_putMessage
@enduml