@startuml
title 主页搜索代码流程-上拉加载
|移动端|
start
:用户点击加载更多或者上拉加载;
:显示正在加载;
:开始网络搜索;
-[#black,dotted]->
|#AntiqueWhite|服务端|
:网络请求服务端搜索查询;
-[#black,dotted]->
|移动端|
:网络搜索结束;
:数据去重;
if (是否有数据) then (否)
    :显示没有更多数据;
    detach
else (是)
    if (搜索数据是否大于20条) then (否)
        :不能上拉加载;
        detach
    else (是)
        :可以上拉加载;
        :网络数据和本地数据比较标记后显示;
    endif
endif
stop
@enduml