@startuml
title 主页搜索代码流程
|移动端|
start
repeat
:点击搜索;
repeat while (是否有搜索内容) is (否)
:开始本地搜索;
-[#black,dotted]->
|#AntiqueWhite|移动端数据库|
:移动端数据库搜索查询;
-[#black,dotted]->
|移动端|
:本地搜索结束;
fork
    :处理本地搜索结果;
    if (是否有数据) then (是)
        :数据去重后，展示数据;
        detach
    else if (是否有网络搜索) then (否)
        :无数据提示;
        detach
        else
         :不提示;
         detach
    endif
fork again
    :处理是否可以网络搜索;
    if (是否有网络) then (否)
        :吐司提示无网络;
        detach
    else if (是否有sim卡) then (否)
            :不能网络搜索;
            detach
    endif
endfork
:开始网络搜索;
-[#black,dotted]->
|#AntiqueWhite|服务端|
:网络请求服务端搜索查询;
-[#black,dotted]->
|移动端|
:网络搜索结束;
:数据去重;
if (是否有数据) then (否)
    :显示没有更多数据;
    detach
else (是)
    if (搜索数据是否大于3条) then (否)
        :不能上拉加载;
        detach
    else (是)
        :可以上拉加载;
        :网络数据和本地数据比较标记后显示;
    endif
endif
stop
@enduml


